Version 3.0.0

diff --git a/tests/test_setup/configure.in b/tests/test_setup/configure.in
--- a/tests/test_setup/configure.in
+++ b/tests/test_setup/configure.in
@@ -58,6 +58,15 @@ WDIR=${PWD}
 STATS_MATLIB_FLAGS=
 STATS_MATLIB_PATH="."
 
+# look for GCEM
+if [ -z ${GCEM_INCLUDE_PATH+x} ]; then
+    echo -e "  \x1B[31m- error: cannot find the GCEM library header files.\033[0m" >&2 ;
+    echo -e "  \x1B[31m-        Please set the GCEM_INCLUDE_PATH variable to the directory containing gcem.hpp. \033[0m" >&2 ;
+    echo -e "  \x1B[31m-        Exiting.\033[0m" >&2 ;
+    echo ""
+    exit 1
+fi
+
 # look for Armadillo
 if [[ "${STATS_LINEAR_ALG_LIB}" == "arma" ]]; then
     if [ -z ${ARMA_INCLUDE_PATH+x} ]; then 
@@ -89,7 +98,7 @@ elif [[ "${STATS_LINEAR_ALG_LIB}" == "eigen" ]]; then
     STATS_MATLIB_FLAGS="-DSTATS_USE_EIGEN"
     STATS_MATLIB_PATH=$EIGEN_INCLUDE_PATH
 else
-    STATS_LINEAR_ALG_LIB="none."
+    STATS_LINEAR_ALG_LIB="none"
 fi
 
 # set optimization flags
@@ -114,7 +123,7 @@ else
     fi
 fi
 
-STATS_WARN_FLAGS="-Wall"
+STATS_WARN_FLAGS="-Wall -Wextra"
 
 # dev build
 
@@ -161,11 +170,18 @@ fi
 
 echo ""
 
+echo "  - GCEM_INCLUDE_PATH set to:"
+echo "    ${GCEM_INCLUDE_PATH}"
+
+echo ""
+
 echo "  - STATS_LINEAR_ALG_LIB set to: ${STATS_LINEAR_ALG_LIB}"
+if [[ "${STATS_LINEAR_ALG_LIB}" != "none" ]]; then 
 echo "  - STATS_MATLIB_PATH set to:"
 echo "    ${STATS_MATLIB_PATH}"
 echo "  - BLAS and Lapack libraries set to:"
 echo "    ${STATS_BLAS_LAPACK}"
+fi
 
 echo ""
 
@@ -206,6 +222,7 @@ sed -e "s|@CXX@|${CXX}|" \
     -e "s|@STATS_BLAS_LAPACK@|${STATS_BLAS_LAPACK}|" \
     -e "s|@STATS_WARN_FLAGS@|${STATS_WARN_FLAGS}|" \
     -e "s|@STATS_OPT_FLAGS@|${STATS_OPT_FLAGS}|" \
+    -e "s|@GCEM_INCLUDE_PATH@|${GCEM_INCLUDE_PATH}|" \
     -e "s|@STATS_INSTALL_INCLUDE_PATH@|${STATS_INSTALL_INCLUDE_PATH}|" \
     Makefile.in > Makefile
 
